### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by joaquinferrero** [berekuk/questhub#154]
@JFerrero

User explorer

Where is the  login?

**Comment by berekuk** [comment]
Hi!
Can you give me more details about your issue? "Sign in" button is in the top right corner, and "Sign up" buttons should work identically to the "Sign in" button.
Also, if the button doesn't work and there are is no visible error, please look in JS console.

**Comment by joaquinferrero** [comment]
El 13/04/15 a las 15:48, Vyacheslav Matyukhin escribió:
>
> Hi!
> Can you give me more details about your issue? "Sign in" button is in the top right corner, and "Sign up" buttons should work identically to the "Sign in" button.
> Also, if the button doesn't work and there are is no visible error, please look in JS console.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/berekuk/questhub/issues/154#issuecomment-92360493>.
>

I clicked"Sign Up"with Twitter.

New page, https://questhub.io/register show:

Welcome to the Questhub, JFerrero!
What would you like to be called?

Login: explorer
Email: explorer@joaquinferrero.com


Pressed "Register" button, and then show

"Sorry, this login is already taken."



JF

**Comment by berekuk** [comment]
I see. Looks like the case sensitivity issue... I'll try to fix it in a few minutes.

**Comment by berekuk** [comment]
Ok, I rolled out a patch. Can you check if it's working now?

**Comment by jferrero** [comment]
Somehow I'm receiving emails for this conversation. I don't know why to be honest.

Note: My name it's also Joaquin Ferrero, we are both IT guys, i knew eventually will cross some user :)

**Comment by berekuk** [comment]
@jferrero, that's because @joaquinferrero named your github login in the first comment, when he referred to his twitter id...
You can mute notifications from the "watch" button menu.

**Comment by joaquinferrero** [comment]
El 13/04/15 a las 17:05, Vyacheslav Matyukhin escribió:
> Ok, I rolled out a patch. Can you check if it's working now?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/berekuk/questhub/issues/154#issuecomment-92392673>.
>


Yes! It's Working!

Thanks, Vyacheslav.
