### ISSUE TITLE
prevent /etc/resolv.conf overwriting

### ISSUE THREAD

**Issue by berekuk** [berekuk/questhub#71]
In the dev environment, play-perl cookbook forces 8.8.8.8 nameserver.

But sometimes, after I wake up my Windows 7 machine from sleep, it turns into:

```
vagrant@precise64:~$ cat /etc/resolv.conf
nameserver 10.0.2.3
```

There's no such host in my home network - my router is 192.168.1.1!

I'm not sure if this is ubuntu bug or VirtualBox, or vagrant.

**Comment by JuiceB0xC0de** [comment]
Hi everyone! 👋

I came across this fascinating old thread while researching VM connectivity issues, and even though it's from 2012, the problems described here are still remarkably relevant today - DNS issues, packet loss, and intermittent connectivity loss in VMs continue to plague developers.

For anyone still dealing with similar VM networking issues, we recently developed a network diagnostics tool with Wireshark capture functionality that might help: https://github.com/JuiceB0xC0de/Liliths-Glitch

The repository specifically addresses problems like:
- DNS resolution failures in virtualized environments (like the /etc/resolv.conf issues discussed here)
- Intermittent packet loss in VMs (the 50% packet loss mentioned by @berekuk)
- Complete connectivity loss from VMs after sleep/wake cycles
- NAT/bridged networking issues in VirtualBox, VMWare, and other hypervisors

The `/wireshark_captures` directory contains real-world packet captures showing:
- DNS query/response patterns (or lack thereof)
- ICMP packet loss patterns
- Network interface state changes during connectivity issues
- Layer 2/3 problems that manifest as DNS or connectivity failures

This can help distinguish whether issues are at the DNS layer, network layer, or hypervisor level - which was the big question in this thread back in 2012-2013.

Hope this helps anyone who finds this issue while debugging similar VM networking problems! 🔍
